### PR TITLE
#6

### PR DESCRIPTION
**Pull request by rupraj-0406**

### CODE REVIEW

**Comment by rupraj-0406** [comment]
1.Creating app.py.
2. Associated classes: Blog, Sl_company (short listing company), Problem, Tag, Intrv_company ( Interview round).
3. In '/blogs' one can add a post, shortlisting round, interview round, problems( inside the shortlisting round), tag (inside problem).
Issues left:
1. Data store in the database but not display main webpage.
2.  Frontend.

**Comment by pshishod2645** [comment]
Hi @rupraj-0406 please withdraw this pull request and create another to branch blogsBackend

**Comment by rupraj-0406** [comment]
Ok I am withdrawing, and creating another one.

**Comment by pshishod2645** [comment]
Hi @rupraj-0406 can you do it now?

**Pull request closed without merging**
