### PR TITLE
feat: SQLAlchemy Models

### PR DESCRIPTION
**Pull request by SubhradeepSS**
**Issue fixed: #3**

**Feature added:**
blog schema defined as a SQLAlchemy model using Flask-SQLAlchemy

### CODE REVIEW

**Comment by pshishod2645** [comment]
@TheLethalCode  Please review and merge this to main.

**Comment by TheLethalCode** [comment]
Hey @SubhradeepSS, this works for a basic structure, and things could be added/changed as necessary later into the project. But, it would be a lot more helpful to the rest of the contributors if you mentioned the changes your PR creates in a bit more detail.

**Comment by SubhradeepSS** [comment]
> 
> 
> Hey @SubhradeepSS, this works for a basic structure, and things could be added/changed as necessary later into the project. But, it would be a lot more helpful to the rest of the contributors if you mentioned the changes your PR creates in a bit more detail.

Sure, will keep that in mind from next time. For this PR though, do I need to explain what I did?

**Comment by TheLethalCode** [comment]
Yep, it would be better. Leave it as a comment so that the others could
understand without delving into the commit history.

**Pull request merged**
