### PR TITLE
appending live search feature

### PR DESCRIPTION
**Pull request by rupraj-0406**

### CODE REVIEW

**Comment by pshishod2645** [comment]
Hi @rupraj-0406, since we'll return only few blogs per page and not all, I don't think there is any use of live search. It's better if the search makes call to the backend.

**Comment by pshishod2645** [comment]
@TheLethalCode shall I close this pull request ?

**Comment by TheLethalCode** [comment]
What exactly do you mean by live search feature?

**Comment by rupraj-0406** [comment]
> What exactly do you mean by live search feature?

It will suggest related search result which are previously enter through the search bar.

**Comment by rupraj-0406** [comment]
> Hi @rupraj-0406, since we'll return only few blogs per page and not all, I don't think there is any use of live search. It's better if the search makes call to the backend.

No no, you are talking about pagination which I have already writen into the code, live search will suggest related search, and here is the screenshot I am talking about:
Screenshot 2020-12-25 212655

**Comment by TheLethalCode** [comment]
@pshishod2645 this is necessary, so I dont see the need to close the PR. He will keep pushing the commits as he finishes the necessary features, and so this is just a draft PR.

**Comment by rupraj-0406** [comment]
Through this updated search engine one can search: tags, author, company through the search bar.

**Comment by rupraj-0406** [comment]
Through this updated search engine one can search: tags, author, company.

**Comment by pshishod2645** [comment]
Hi @rupraj-0406, I've reviewed all your commits. And seems like you've ignored the work done in main completely. This is not how it is done, you have to append changes to whatever other people are working on. The best way I see now is you clone the repo again in a new directory, see what has been done, and then only append the changes that are still relevant. I'm sorry to say but most of the work you did was already done. Please contact me on slack in case of any issues. I'm closing this pull request for now. Also, we can't merge your last pull request because of aforementioned reasons, therefore I'll be deleting this branch completely once you setup the right version of repo again.

**Pull request closed without merging**
